apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # レプリカ数は初期値1なので実は書かなくてもOK(明示)
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80